### ISSUE TITLE
get value from proxy

### ISSUE THREAD

**Issue by mun24** [patriksimek/vm2#161] opened 2018-10-11 16:08 UTC
Unable to get value from proxy, for example:
result = vm.run("let i={y: new Date()};i");

result = Proxy {y: }
 [[Handler]] = Object
 [[Target]] = Object
  y = Thu Oct 11 2018 12:01:40 GMT-0400 (Eastern Daylight Time) {}
  	__proto__ = Object {constructor: ,__defineGetter__: ,__defineSetter__: ,hasOwnProperty: ,__lookupGetter__: ,...}
[[IsRevoked]] = false
How to get new Date() value. result.y is proxy.

**Comment by daliwali** [comment] 2018-10-18 08:57
Duplicate of https://github.com/patriksimek/vm2/issues/62

**Closed** 2019-01-26 22:05 UTC
