### ISSUE TITLE
Breaking change in `NodeVM.run` in v3.9.6

### ISSUE THREAD

**Issue by qooban** [patriksimek/vm2#411] opened 2022-02-21 08:16 UTC
Looks like there was a breaking change in `v3.9.6`.

The following part of our code:
```
            const script = `
                    import backend from '${backendFile}';
                    module.exports = new Promise((resolve, reject) => {
                       // ... truncated ...
                     });`;

            return vm.run(script, pathlib.resolve(`${process.cwd()}/${widgetId}`));
```
(taken from https://github.com/cloudify-cosmo/cloudify-stage/blob/master/backend/handler/BackendHandler.ts)
stopped working. We see the following error:
```
Cannot find module '/(...)/cloudify-stage/widgets/executions/backend.ts'
```
It comes from the first line of shared code `import backend from '${backendFile}';`.

In `3.9.5` everything worked fine.

Seems like:
1. `vm.run` was changed within https://github.com/patriksimek/vm2/commit/532120d5cdec7da8225fc6242e154ebabc63fe4d and it is no longer available in the shape we were using it (`run(js: string, path?: string): any;`)
2. Custom compiler passed to `NodeVM` (https://github.com/cloudify-cosmo/cloudify-stage/blob/e8e2d1a0f248d9d7dc7b244d8719471e22fa357e/backend/handler/BackendHandler.ts#L120) is not used?
3. Issue might be related to #409

**Comment by XmiliaH** [comment] 2022-02-21 08:22
This seems to be related to changes to the resolver. This has nothing to do with
1) This just allows to override options on a per run bases but still allows the old calling convention.
2) The custom compiler is still used.
3) This would throw a SyntaxError.

Could you share the NodeVM options you are using?

**Comment by qooban** [comment] 2022-02-21 08:25
@XmiliaH Thanks for quick response.

Sure, there are `NodeVM` options:
```
            const vm = new NodeVM({
                sandbox: {
                    _,
                    widgetId,
                    BackendRegistrator
                },
                require: {
                    context: 'sandbox',
                    external: getConfig().app.widgets.allowedModules
                },
                compiler: source => ts.transpile(source, tsConfig.compilerOptions),
                sourceExtensions: ['ts']
            });
```
(ref.: https://github.com/cloudify-cosmo/cloudify-stage/blob/master/backend/handler/BackendHandler.ts)

**Comment by XmiliaH** [comment] 2022-02-21 08:28
What would `getConfig().app.widgets.allowedModules` evaluate to?

**Comment by XmiliaH** [comment] 2022-02-21 08:43
There was a problem with `sourceExtensions` in v3.9.6. Could you test this with the latest version (v3.9.8)?

**Comment by XmiliaH** [comment] 2022-02-21 08:59
This is intended behavior. When supplying `external` in the options modules can only load files in the same or child directories of the module or from a module found in `external`. This is also checked now for absolute paths, since it was a bug that this was not checked before. If you want to allow to load any file `external` should be `true` and the `root` option should be used to specify from which directories files can be loaded.

**Comment by qooban** [comment] 2022-02-21 10:58
@XmiliaH 

I appreciate your quick responses. Please find my answers below.

> What would `getConfig().app.widgets.allowedModules` evaluate to?

`["lodash", "body/json", "elkjs"]`

> There was a problem with `sourceExtensions` in v3.9.6. Could you test this with the latest version (v3.9.8)?

Tested. The problem is the same in all newer than `3.9.5`.

> This is intended behavior. When supplying `external` in the options modules can only load files in the same or child directories of the module or from a module found in `external`. This is also checked now for absolute paths, since it was a bug that this was not checked before. If you want to allow to load any file `external` should be `true` and the `root` option should be used to specify from which directories files can be loaded.

Hmm... It worked before. I didn't expect breaking change in patch version.
We need to support only predefined set of modules (see list above - `allowedModules`) and importing the main script file (see `backendFile` - it can be something like: `'/(...)/cloudify-stage/widgets/executions/backend.ts'`)

Changing `external` to `true` and setting `root` does not help.

**Comment by qooban** [comment] 2022-02-21 14:25
OK, this way it seems to work. Thanks for sharing!

**Comment by XmiliaH** [comment] 2022-02-24 21:29
Since this is intended behavior and was a long time bug which rendered the external option useless, I will close this issue.

**Closed by XmiliaH** 2022-02-24 21:29 UTC
