### ISSUE TITLE
How to use/call 'require'

### ISSUE THREAD

**Issue by dekhaus** [patriksimek/vm2#25] opened 2016-03-23 18:57 UTC
Hi

I'm trying to use vm2 in order to allow user written scripts which run in vm2 to use 'require'.  I added 

  var request = require('request')

to the top of my 'userScript' and then added the userScript to vm2's sandbox.  When I try and run the vm by doing ...

  var result = vm2.run(helper)

my node process crashes with a 'require is not defined' error.

How do I call 'require' statements in user scripts ?

More details on this question can be found in another question (https://github.com/patriksimek/vm2/issues/20)

Thanks
Dave

**Comment by patriksimek** [comment] 2016-04-06 21:05
Duplicate of #20

**Closed by patriksimek** 2016-04-06 21:05 UTC
