### ISSUE TITLE
Exception when parsing public class fields since v3.9.6 

### ISSUE THREAD

**Issue by andyMrtnzP** [patriksimek/vm2#412] opened 2022-02-24 19:42 UTC
Since `v3.9.6`, vm2 throws a `SyntaxError: Unexpected token` whenever it is parsing classes with public fields.

## Example

``` javascript
//index.js

const { NodeVM } = require("vm2");
const vm = new NodeVM({
  require: {
    external: true,
    root: "./",
  },
});

vm.run(
  `
  class Book {
    title = null;
    author = null;
  
    constructor({ title, author }) {
      this.title = title;
      this.author = author;
    }
  }
  
  const book = new Book({title: "Ulysses", author: "James Joyce"});
  console.log(book);
`, "vm.js");

```

Running this throws a

``` powershell
> node .\index.js

node_modules\vm2\lib\transformer.js:41
                throw e;
                ^

SyntaxError: Unexpected token (3:10)
    at Parser.pp$4.raise (C:\Users\Andy\Projects\bowser\vm2est\node_modules\acorn\dist\acorn.js:3460:15)
    at Parser.pp$9.unexpected (C:\Users\Andy\Projects\bowser\vm2est\node_modules\acorn\dist\acorn.js:756:10)
    at Parser.pp$9.expect (C:\Users\Andy\Projects\bowser\vm2est\node_modules\acorn\dist\acorn.js:750:28)
    at Parser.pp$5.parseMethod (C:\Users\Andy\Projects\bowser\vm2est\node_modules\acorn\dist\acorn.js:3222:10)
    at Parser.pp$8.parseClassMethod (C:\Users\Andy\Projects\bowser\vm2est\node_modules\acorn\dist\acorn.js:1511:37)
    at Parser.pp$8.parseClassElement (C:\Users\Andy\Projects\bowser\vm2est\node_modules\acorn\dist\acorn.js:1469:12)
    at Parser.pp$8.parseClass (C:\Users\Andy\Projects\bowser\vm2est\node_modules\acorn\dist\acorn.js:1387:26)
    at Parser.pp$8.parseStatement (C:\Users\Andy\Projects\bowser\vm2est\node_modules\acorn\dist\acorn.js:902:19)
    at Parser.pp$8.parseTopLevel (C:\Users\Andy\Projects\bowser\vm2est\node_modules\acorn\dist\acorn.js:813:23)
    at Parser.parse (C:\Users\Andy\Projects\bowser\vm2est\node_modules\acorn\dist\acorn.js:586:17) {
  pos: 26,
  loc: Position { line: 3, column: 10 },
  raisedAt: 27
}
```

But if the public fields are removed, it works like a charm

``` javascript
vm.run(
  `
  class Book {
    constructor({ title, author }) {
      this.title = title;
      this.author = author;
    }
  }
  
  const book = new Book({title: "Ulysses", author: "James Joyce"});
  console.log(book);
`, "vm.js");
```
``` powershell
> node .\index.js
{ title: 'Ulysses', author: 'James Joyce' }
```

**Comment by XmiliaH** [comment] 2022-02-24 19:44
Duplicate of https://github.com/patriksimek/vm2/issues/409.

**Closed by XmiliaH** 2022-02-24 19:44 UTC
