### ISSUE TITLE
Throws ERR_INTERNAL_ASSERTION

### ISSUE THREAD

**Issue by Consoli0** [patriksimek/vm2#310] opened 2020-08-04 21:10 UTC
I'm playing around with VM2 a bit, and I got an internal assertion error, before submitting an issue to Node.JS, I'd like to know if this is caused by a problem with VM2.

Error:
```
Error [ERR_INTERNAL_ASSERTION]: This is caused by either a bug in Node.js or incorrect 
usage of Node.js internals.
Please open an issue with this stack trace at https://github.com/nodejs/node/issues    

    at assert (internal/assert.js:14:11)
    at getKeys (internal/util/inspect.js:627:7)
    at formatRaw (internal/util/inspect.js:858:12)
    at formatValue (internal/util/inspect.js:751:10)
    at formatProperty (internal/util/inspect.js:1603:11)
    at formatRaw (internal/util/inspect.js:963:9)
    at formatValue (internal/util/inspect.js:751:10)
    at inspect (internal/util/inspect.js:289:10)
    at formatWithOptionsInternal (internal/util/inspect.js:1918:40)
    at formatWithOptions (internal/util/inspect.js:1802:10) {
  code: 'ERR_INTERNAL_ASSERTION'
```

Code:
```ts
import * as VM from 'vm2';

const vm = new VM.NodeVM({
  timeout: 5000,
  sandbox: {
    a: 1,
    b: 2,
  },
});

console.log(vm.run(`console.log(this)`));
console.log(vm.run(`'hello'`));
console.log(vm.run(`a`));
console.log(vm.run(`a = 5`));
console.log(vm.run(`b = ['yo']`));
console.log(vm.run(`let c = 8`));
console.log(vm.run(`const d = -5`));
console.log(vm.run(`global.e = 9`));
console.log(vm.run(`globalThis.f = 10`));
console.log(vm.run(`this.g = 11`));
console.log(vm.sandbox);
```

**Comment by XmiliaH** [comment] 2020-08-04 21:14
The problem is fixed in the master branch.

**Comment by kyledetella** [comment] 2020-09-13 02:23
I ran into the same issue. For now, I installed directly from the latest SHA `npm i -D patriksimek/vm2#a81e12ce3950f41cbc3199bc03dbb7cd9bcb0121` and the problem was fixed.

**Comment by janhaa** [comment] 2020-09-28 21:03
@XmiliaH Out of interest, which PR fixed the issue?

**Comment by XmiliaH** [comment] 2020-09-28 21:09
@janhaa I think it was https://github.com/patriksimek/vm2/pull/301

**Closed** 2021-05-13 09:54 UTC
Labels: bug, confirmed, duplicate
