### ISSUE TITLE
Issue assigning functions when using expr-eval

### ISSUE THREAD

**Issue by strykeio** [patriksimek/vm2#343] opened 2021-03-24 17:44 UTC
Hi,

I am using [expr-eval](https://github.com/silentmatt/expr-eval) in the code I am executing inside my NodeVM. 
The purpose of this module is to evaluate mathematical expressions. One of the features allows specifying your own JS functions, which I am doing for very specific tasks. The way in which this is done is by doing the following: 

```
const Parser = require('expr-eval').Parser;
const parser = new Parser();
parser.functions.myFunc = (x) => { return x * 2 };
return parser.evaluate('4 + myFunc(10)');
```

When executing this code outside VM2 everything works fine. However, when executing it under a NodeVM parser.functions.myFunc is not assigned, resulting in an error when myFunc is called because it is `undefined`.

Why is this happening? Is there a way to allow this assignment? 

Thanks for your help and great module!
Edoardo.

**Comment by XmiliaH** [comment] 2021-04-08 00:27
I think the problem here is that `Parser` is readonly and so is `parser` resulting in `myFunc` never being written.

**Comment by XmiliaH** [comment] 2022-02-08 13:42
As this is intended behavior I will close this issue.

**Closed by XmiliaH** 2022-02-08 13:42 UTC
Labels: confirmed
