### ISSUE TITLE
Uint8Array unable to parse ArrayBuffer

### ISSUE THREAD

**Issue by garymathews** [patriksimek/vm2#478] opened 2022-10-05 04:00 UTC
- Passing a valid and non-empty `ArrayBuffer` into the `Uint8Array` constructor returns a `Uint8Array` of zero length
```JS
import { NodeVM } from 'vm2';

const vm = new NodeVM();
vm.run(`
    const buffer = Buffer.from('SGVsbG8gV29ybGQh', 'base64');
    console.log('buffer.buffer', buffer.buffer);
    console.log('buffer.byteOffset', buffer.byteOffset);
    console.log('buffer.byteLength', buffer.byteLength);
    console.log('buffer.length', buffer.length);

    const data = new Uint8Array(buffer.buffer, buffer.byteOffset, buffer.byteLength);
    console.log('data.length', data.length);
`);
```
```
buffer.buffer ArrayBuffer {
  [Uint8Contents]: <27 75 73 ... 8092 more bytes>,
  byteLength: 8192
}
buffer.byteOffset 2312
buffer.byteLength 12
buffer.length 12
data.length 0
```
`data.length` should not be zero, a workaround I've found is to just pass the `Buffer` and not the `ArrayBuffer`. However, this is not the recommended way (see https://nodejs.org/api/buffer.html#bufbyteoffset)

I encountered this due to emscripten Base64 decoding of WASM https://github.com/emscripten-core/emscripten/blob/main/src/base64Decode.js#L42

**Comment by XmiliaH** [comment] 2022-10-05 05:20
Duplicate of https://github.com/patriksimek/vm2/issues/422.

**Closed by XmiliaH** 2022-10-05 05:20 UTC
