### ISSUE TITLE
require is not defined inside eval

### ISSUE THREAD

**Issue by ayZagen** [patriksimek/vm2#379] opened 2021-11-25 12:45 UTC
This issue occurs on version 3.9.4 and 3.9.5.

Following code snippet fails with the error `ReferenceError: require is not defined`.

```js
const {NodeVM} = require('vm2');
 
const vm = new NodeVM({
    console: 'inherit',
    eval: true,
    require: true
});
vm.run('eval("console.log(require)")');
```

**Comment by XmiliaH** [comment] 2021-11-25 12:49
This is caused by the replacement of `eval` to verify the code. However, this results in all `eval` calls not being direct and therefore with no access to the variables of the outer scope. Unfortunately  this cannot be fixed by this project.

**Closed** 2022-02-08 13:39 UTC
Labels: wontfix, confirmed
