### ISSUE TITLE
vm.run().then throw an error on version @3.9.4

### ISSUE THREAD

**Issue by DennisJames** [patriksimek/vm2#370] opened 2021-10-13 04:14 UTC
```js
const { NodeVM } = require('vm2');
const vm = new NodeVM({
});


const data = vm.run(`module.exports = (async function () { return 'vv'; })()`);
console.log(data.__proto__)
data.then(console.log).catch(console.error)
```

run this code with node@12.x will get :
```shell
data.then(console.log).catch(console.error)
     ^

TypeError: Method Promise.prototype.then called on incompatible receiver [object Object]
    at Proxy.then (<anonymous>)
```

**Comment by XmiliaH** [comment] 2021-10-13 05:16
Duplicate of https://github.com/patriksimek/vm2/issues/368. This is currently fixed in head.

**Comment by joelgriffith** [comment] 2021-10-17 17:39
@XmiliaH are you able to do npm releases? There's a good swathe of dependabot and snyk updates that are broken due to this patch needing to be released.

Ping at @patriksimek as well.

**Closed as completed** 2021-10-17 17:59 UTC
Labels: duplicate, confirmed
